import { Component, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { WeatherForecast } from './models/weather-forecast';
import { WeatherForecastService } from './services/weather-forecast.service';

/**
 * WeatherForecastService and WeatherForecast are both generated by KY.Generator from
 * WeatherForecastController, driven by the [GenerateAngularService] annotation on the
 * controller. Nothing in this component is hand-wired to the API - the service already
 * knows the route and the response shape.
 */
@Component({
  selector: 'app-root',
  imports: [DatePipe],
  templateUrl: './app.html'
})
export class App {
  private readonly service = inject(WeatherForecastService);

  protected readonly forecasts = signal<WeatherForecast[]>([]);
  protected readonly error = signal<string | undefined>(undefined);

  public constructor() {
    this.service.get().subscribe({
      next: (result) => this.forecasts.set(result),
      error: (error: unknown) => this.error.set(String(error))
    });
  }
}
