// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 8.1.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class TypeToRead {
    public stringProperty: string;
    public numberProperty: number;

    public constructor(init?: Partial<TypeToRead>) {
        Object.assign(this, init);
    }
}

// outputid:f473e1d8-04b6-4dbc-92ff-db4d63bfe67d
