// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 7.0.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// ReSharper disable All

public partial class Person
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string? Birthday { get; set; }
    public int Age { get; set; }
}

// outputid:f1500a12-5a64-4e7d-9e36-4336d7ca0ad8
