// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 8.5.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// ReSharper disable All

using System.CodeDom.Compiler;

[GeneratedCode("KY.Generator", "8.5.0.0")]
public partial class Person
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Birthday { get; set; }
    public int Age { get; set; }
    public string Address { get; set; }
}

// outputid:24a70ace-e281-41c6-8732-ac157e92e94a
