// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 9.0.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

import { EnumToIgnore } from "./";
import { TypeToIgnore } from "./";
import { GenerateOnlySubTypes } from "./generate-only-sub-types";

export class TypeToRead {
    public typeToIgnoreField?: TypeToIgnore;
    public stringProperty?: string;
    public numberProperty?: number;
    public typeToIgnoreProperty?: TypeToIgnore;
    public enumToIgnoreProperty?: EnumToIgnore;
    public generateOnlySubTypes?: GenerateOnlySubTypes;
}

// outputid:0069e9c6-1a9c-4b27-ac11-56d1413e4d18
