// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 5.6.0.0
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// tslint:disable

import { EnumToIgnore } from "./enum-to-ignore";
import { TypeToIgnore } from "./type-to-ignore";

export class TypeToRead {
    public typeToIgnoreField: TypeToIgnore;
    public stringProperty: string;
    public numberProperty: number;
    public typeToIgnoreProperty: TypeToIgnore;
    public enumToIgnoreProperty: EnumToIgnore;
}