// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 10.0.1.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class LegacyWeatherForecast {
    public date: Date;
    public temperatureC: number;
    public summary?: string;

    public constructor(init?: Partial<LegacyWeatherForecast>) {
        Object.assign(this, init);
    }
}

// outputid:4c1f0e2a-9b4d-4e7a-8c31-6f2d5b0a7e14
