// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 7.5.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export enum ConnectionStatus {
    connecting = 0,
    connected = 1,
    sleeping = 2,
    disconnected = 3
}

export const ConnectionStatusValues = [0, 1, 2, 3];
export const ConnectionStatusNames = ["connecting", "connected", "sleeping", "disconnected"];
export const ConnectionStatusValueMapping: { [key: number]: string } = { 0: "connecting", 1: "connected", 2: "sleeping", 3: "disconnected" };
export const ConnectionStatusNameMapping: { [key: string]: number } = { "connecting": 0, "connected": 1, "sleeping": 2, "disconnected": 3 };

// outputid:13aebde4-a1a8-4508-9cb6-7cbd78013e56
