// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 10.0.1.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// ReSharper disable All

using System.CodeDom.Compiler;

namespace CustomModule.Console.Generated
{
    [GeneratedCode("KY.Generator", "10.0.1.0")]
    public partial class Greeter
    {
        public static void SayHello()
        {
            System.Console.WriteLine("Hello World!");
        }
    }
}

// outputid:5168d506-dd1d-4851-ab6c-628732ade155
