// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 7.0.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// ReSharper disable All

using System;

namespace Hello.World
{
    public partial class Program
    {
        public void Write()
        {
            Console.WriteLine("Hello World!");
        }
    }
}

