<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="KY.Generator" Version="10.0.1-preview.6" />
      <PackageReference Include="KY.Generator.Angular" Version="10.0.1-preview.6" />
      <PackageReference Include="KY.Generator.AspDotNet" Version="10.0.1-preview.6" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ChangeReturnType\ChangeReturnType.csproj" />
    </ItemGroup>

</Project>
