// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 6.7.2.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class TypeToRead {
    public stringProperty: string;
    public numberProperty: number;
}

// outputid:1387495c-f857-4889-b5dd-ddb10505f499
