// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 10.1.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class TypeToRead {
    public stringProperty: string = "";
    public numberProperty: number = 0;

    public constructor(init?: Partial<TypeToRead>) {
        Object.assign(this, init);
    }
}

// outputid:1387495c-f857-4889-b5dd-ddb10505f499
