// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 7.0.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// ReSharper disable All

using System.IO;
using Newtonsoft.Json;

namespace KY.Generator.Examples.Json
{
    public partial class ComplexReader
    {
        public static Complex Load(string fileName)
        {
            return Parse(File.ReadAllText(fileName));
        }

        public static Complex Parse(string json)
        {
            return JsonConvert.DeserializeObject<Complex>(json);
        }
    }
}

