// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 7.2.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class Simple {
    public stringProperty: string;
    public numberProperty: number;
    public booleanProperty: boolean;

    public constructor(init?: Partial<Simple>) {
        Object.assign(this, init);
    }
}

// outputid:b7fab864-b0a6-4be6-bc07-794f04ca61cd
