// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 8.1.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// ReSharper disable All

using System.CodeDom.Compiler;

[GeneratedCode("KY.Generator", "8.1.0.0")]
public partial class Simple
{
    public string StringProperty { get; set; }
    public int NumberProperty { get; set; }
    public bool BooleanProperty { get; set; }
}

// outputid:b7fab864-b0a6-4be6-bc07-794f04ca61cd
