// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 6.2.2.0
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// tslint:disable

export class Class1 {
    public static readonly stringProperty: string = "Value-One";
    public static readonly numberProperty: number = 7;

    public constructor(init: Partial<Class1> = undefined) {
        Object.assign(this, init);
    }
}

// outputid:fae04ec0-301f-11d3-bf4b-00c04f79efbc
