// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 4.0.0.0
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// tslint:disable

import { Value } from "../models/value";
import { HttpClient } from "@angular/common/http";
import { Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { Subject } from "rxjs";

@Injectable({
    providedIn: "root"
})
export class ValuesCoreService {
    private readonly http: HttpClient;
    public serviceUrl: string = "";

    public constructor(http: HttpClient) {
        this.http = http;
    }

    public get(httpOptions: {} = undefined): Observable<string[]> {
        let subject = new Subject<string[]>();
        this.http.get<string[]>(this.serviceUrl + "/api/values", httpOptions).subscribe(result => {
            subject.next(result);
            subject.complete();
        }, error => subject.error(error));
        return subject;
    }

    public get2(id: number, httpOptions: {} = undefined): Observable<Value> {
        let subject = new Subject<Value>();
        this.http.get<Value>(this.serviceUrl + "/api/values/" + id, httpOptions).subscribe(result => {
            subject.next(result);
            subject.complete();
        }, error => subject.error(error));
        return subject;
    }

    public post(value: Value, httpOptions: {} = undefined): Observable<void> {
        let subject = new Subject<void>();
        this.http.post<void>(this.serviceUrl + "/api/values", value, httpOptions).subscribe(() => {
            subject.next();
            subject.complete();
        }, error => subject.error(error));
        return subject;
    }

    public put(id: number, value: Value, httpOptions: {} = undefined): Observable<void> {
        let subject = new Subject<void>();
        this.http.put<void>(this.serviceUrl + "/api/values/" + id, value, httpOptions).subscribe(() => {
            subject.next();
            subject.complete();
        }, error => subject.error(error));
        return subject;
    }

    public delete(id: number, httpOptions: {} = undefined): Observable<void> {
        let subject = new Subject<void>();
        this.http.delete<void>(this.serviceUrl + "/api/values/" + id, httpOptions).subscribe(() => {
            subject.next();
            subject.complete();
        }, error => subject.error(error));
        return subject;
    }

    public check(httpOptions: {} = undefined): Observable<void> {
        let subject = new Subject<void>();
        this.http.get<void>(this.serviceUrl + "/api/values/check", httpOptions).subscribe(() => {
            subject.next();
            subject.complete();
        }, error => subject.error(error));
        return subject;
    }

    public checkInterface(httpOptions: {} = undefined): Observable<void> {
        let subject = new Subject<void>();
        this.http.get<void>(this.serviceUrl + "/api/values/checkinterface", httpOptions).subscribe(() => {
            subject.next();
            subject.complete();
        }, error => subject.error(error));
        return subject;
    }
}