// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 6.6.2.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class WeatherForecast {
    public date: Date;
    public temperatureC: number;
    public temperatureF: number;
    public summary: string;

    public constructor(init: Partial<WeatherForecast> = undefined) {
        Object.assign(this, init);
    }
}

// outputid:9a19103f-16f7-4668-be54-9a1e7a4f7556
