// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 10.0.1.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class Constants {
    public static readonly staticStringProperty: string = "Static-Value";
    public static readonly staticNumberProperty: number = 9;
    public static readonly stringProperty: string = "Value-One";
    public static readonly numberProperty: number = 7;

    public constructor(init?: Partial<Constants>) {
        Object.assign(this, init);
    }
}

// outputid:41084dd2-495e-4078-bfc1-ca5193667c60
