//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KY.Generator.Reflection.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KY.Generator.Reflection.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // tslint:disable
        ///
        ///import { OneInterfaceType } from &quot;./one-interface-type&quot;;
        ///import { ISecond } from &quot;./second.interface&quot;;
        ///
        ///export class BaseClassAndOneInterfaceType extends OneInterfaceType implements ISecond {
        ///    public secondProperty: string;
        ///}.
        /// </summary>
        internal static string base_class_and_one_interface_type_ts {
            get {
                return ResourceManager.GetString("base_class_and_one_interface_type_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // tslint:disable
        ///
        ///import { OneInterfaceType } from &quot;./one-interface-type&quot;;
        ///import { ISecond } from &quot;./second.interface&quot;;
        ///import { IThird } from &quot;./third.interface&quot;;
        ///
        ///export class BaseClassAndTwoInterfacesType extends OneInterfaceType implements ISecond, IThird {
        ///    public secondProperty: string;
        ///    public thirdProperty: string;
        ///}.
        /// </summary>
        internal static string base_class_and_two_interfaces_type_ts {
            get {
                return ResourceManager.GetString("base_class_and_two_interfaces_type_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // tslint:disable
        ///
        ///export interface IFirst {
        ///    firstProperty: string;
        ///}.
        /// </summary>
        internal static string first_interface_ts {
            get {
                return ResourceManager.GetString("first_interface_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // tslint:disable
        ///
        ///import { IFirst } from &quot;./first.interface&quot;;
        ///
        ///export interface IInheritFirst extends IFirst {
        ///    firstInheritedProperty: string;
        ///}.
        /// </summary>
        internal static string inherit_first_interface_ts {
            get {
                return ResourceManager.GetString("inherit_first_interface_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // tslint:disable
        ///
        ///import { IInheritFirst } from &quot;./inherit-first.interface&quot;;
        ///
        ///export class InheritInterfaceType implements IInheritFirst {
        ///    public firstProperty: string;
        ///    public firstInheritedProperty: string;
        ///}.
        /// </summary>
        internal static string inherit_interface_type_ts {
            get {
                return ResourceManager.GetString("inherit_interface_type_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // tslint:disable
        ///
        ///import { IFirst } from &quot;./first.interface&quot;;
        ///
        ///export class OneInterfaceType implements IFirst {
        ///    public firstProperty: string;
        ///}.
        /// </summary>
        internal static string one_interface_type_ts {
            get {
                return ResourceManager.GetString("one_interface_type_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // tslint:disable
        ///
        ///export interface ISecond {
        ///    secondProperty: string;
        ///}.
        /// </summary>
        internal static string second_interface_ts {
            get {
                return ResourceManager.GetString("second_interface_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // tslint:disable
        ///
        ///export class SubType {
        ///    public property: string;
        ///}.
        /// </summary>
        internal static string subtype {
            get {
                return ResourceManager.GetString("subtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // tslint:disable
        ///
        ///export interface IThird {
        ///    thirdProperty: string;
        ///}.
        /// </summary>
        internal static string third_interface_ts {
            get {
                return ResourceManager.GetString("third_interface_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // tslint:disable
        ///
        ///import { IFirst } from &quot;./first.interface&quot;;
        ///import { ISecond } from &quot;./second.interface&quot;;
        ///
        ///export class TwoInterfacesType implements IFirst, ISecond {
        ///    public firstProperty: string;
        ///    public secondProperty: string;
        ///}.
        /// </summary>
        internal static string two_interfaces_type_ts {
            get {
                return ResourceManager.GetString("two_interfaces_type_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // tslint:disable
        ///
        ///import { SubType } from &quot;./sub-type&quot;;
        ///
        ///export class Types {
        ///    public stringField: string;
        ///    public intField: number;
        ///    public dateTimeField: Date;
        ///    public stringProperty: string;
        ///    public shortProperty: number;
        ///    public uShortProperty: number;
        ///    public intProperty: number;
        ///    public uIntProperty: number;
        ///    public longProperty: number;
        ///    public uLongProperty: number;
        ///    public floatProperty: number;
        ///    public doubleProperty: number;
        ///    public boolPro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string types {
            get {
                return ResourceManager.GetString("types", resourceCulture);
            }
        }
    }
}
