// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 7.4.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class TypeToRead {
    public stringProperty: string;
    public numberProperty: number;
}

// outputid:8c8a1d3a-034b-4633-bf8c-aa6ac39af861
