using System.Reflection;
using KY.Core;
using KY.Generator.Documentation;
using KY.Generator.Models;
using KY.Generator.Transfer;

namespace KY.Generator;

public class GeneratorOptionsFactory : IOptionsFactory, IConfigurableOptionsFactory
{
    public string SettingsSection => "options";
    public string SettingsSectionDescription => "Options that apply to every generated language";
    public Type OptionsType => typeof(GeneratorOptions);

    /// <summary>
    /// Only the options that are inherited down the option tree can be configured. The ones that describe a single
    /// type or member - <see cref="GeneratorOptions.Never"/>, <see cref="GeneratorOptions.Rename"/>, ... - read their
    /// own value only, so a value set on the global options would never be seen
    /// </summary>
    public IReadOnlyList<SettingsOption> SettingsOptions { get; } =
    [
        SettingsOption.For<GeneratorOptions, bool>("addHeader", true, "Write the <auto-generated> header into every generated file",
                                                 (options, value) => options.AddHeader = value, options => options.AddHeader),
        SettingsOption.For<GeneratorOptions, bool>("addHeaderVersion", true, "Write the version of the generator into the <auto-generated> header",
                                                 (options, value) => options.AddHeaderVersion = value, options => options.AddHeaderVersion),
        SettingsOption.For<GeneratorOptions, bool>("forceOverwrite", false, "Overwrite files that were changed by hand",
                                                 (options, value) => options.ForceOverwrite = value, options => options.ForceOverwrite),
        SettingsOption.For<GeneratorOptions, bool>("formatNames", true, "Format the generated names in the casing of the target language",
                                                 (options, value) => options.FormatNames = value, options => options.FormatNames),
        SettingsOption.For<GeneratorOptions, string>("formatter", null, "Command line that post-processes every generated file, $file is replaced by its path",
                                                     (options, value) => options.Formatter = value, options => options.Formatter,
                                                     "prettier --write $file"),
        SettingsOption.For<GeneratorOptions, Dictionary<string, string>>("lintSuppression", null,
                                                                        "The comment that switches the linter off, by language name. Use \"\" for every language without an own entry",
                                                                        (options, value) => value.ForEach(entry => options.AddToLintSuppression(entry.Value, entry.Key)),
                                                                        options => options.LintSuppression,
                                                                        new Dictionary<string, string> { ["typescript"] = "/* eslint-disable */" }),
        SettingsOption.For<GeneratorOptions, string>("modelOutput", null, "Relative path the generated models are written to",
                                                     (options, value) => options.ModelOutput = value, options => options.ModelOutput,
                                                     "Output/Models"),
        SettingsOption.For<GeneratorOptions, bool>("noOptional", false, "Never generate optional members",
                                                 (options, value) => options.NoOptional = value, options => options.NoOptional),
        SettingsOption.For<GeneratorOptions, bool>("nullable", false, "Generate nullable types",
                                                 (options, value) => options.Nullable = value, options => options.Nullable),
        SettingsOption.For<GeneratorOptions, bool>("optionalFields", false, "Generate all fields as optional",
                                                 (options, value) => options.OptionalFields = value, options => options.OptionalFields),
        SettingsOption.For<GeneratorOptions, bool>("optionalProperties", false, "Generate all properties as optional",
                                                 (options, value) => options.OptionalProperties = value, options => options.OptionalProperties),
        SettingsOption.For<GeneratorOptions, bool>("preferInterfaces", false, "Generate interfaces instead of classes",
                                                 (options, value) => options.PreferInterfaces = value, options => options.PreferInterfaces),
        SettingsOption.For<GeneratorOptions, bool>("skipNamespace", false, "Generate without a namespace",
                                                 (options, value) => options.SkipNamespace = value, options => options.SkipNamespace),
        SettingsOption.For<GeneratorOptions, bool>("withOptionalProperties", false, "Add an optional variant for every property",
                                                 (options, value) => options.WithOptionalProperties = value, options => options.WithOptionalProperties),
        SettingsOption.Group<GeneratorOptions>("formatting", "Casing, indentation and the other details of the written code",
                                             options => options.Formatting,
                                             SettingsOption.FromProperties(new FormattingOptions(),
                                                                          // The only formatting option without a default
                                                                          new Dictionary<string, object> { ["allowedSpecialCharacters"] = "_$" }))
    ];

    public bool CanCreate(Type optionsType)
    {
        return optionsType == typeof(GeneratorOptions);
    }

    public object Create(Type optionsType, object key, object? parent, object global)
    {
        return new GeneratorOptions(parent as GeneratorOptions, global as GeneratorOptions, key);
    }

    public object CreateGlobal(Type optionsType, object key, object? parent)
    {
        return key switch
        {
            Assembly assembly => this.CreateFromCustomAttributes(assembly.GetCustomAttributes(), assembly, parent as GeneratorOptions),
            MemberInfo member => this.CreateFromCustomAttributes(member.GetCustomAttributes(), member, parent as GeneratorOptions),
            ParameterInfo parameter => this.CreateFromCustomAttributes(parameter.GetCustomAttributes(), parameter, parent as GeneratorOptions),
            Options.RootKey => new GeneratorOptions(parent as GeneratorOptions, null, "global"),
            _ => new GeneratorOptions(parent as GeneratorOptions, null, key)
            // _ => throw new InvalidOperationException($"Could not create {nameof(GeneratorOptions)} {key.GetType()}")
        };
    }

    private GeneratorOptions CreateFromCustomAttributes(IEnumerable<Attribute> customAttributes, Assembly assembly, GeneratorOptions? parent)
    {
        GeneratorOptions options = this.CreateFromCustomAttributes(customAttributes, (object)assembly, parent);
        this.UpdateFromDocumentation(options, DocumentationReader.Get(assembly));
        return options;
    }

    private GeneratorOptions CreateFromCustomAttributes(IEnumerable<Attribute> customAttributes, MemberInfo member, GeneratorOptions? parent)
    {
        GeneratorOptions options = this.CreateFromCustomAttributes(customAttributes, (object)member, parent);
        this.UpdateFromDocumentation(options, DocumentationReader.Get(member));
        return options;
    }

    private GeneratorOptions CreateFromCustomAttributes(IEnumerable<Attribute> customAttributes, ParameterInfo parameter, GeneratorOptions? parent)
    {
        GeneratorOptions options = this.CreateFromCustomAttributes(customAttributes, (object)parameter, parent);
        this.UpdateFromDocumentation(options, DocumentationReader.Get(parameter));
        return options;
    }

    private GeneratorOptions CreateFromCustomAttributes(IEnumerable<Attribute> customAttributes, object key, GeneratorOptions? parent)
    {
        GeneratorOptions options = new(parent, null, key);
        foreach (Attribute attribute in customAttributes)
        {
            switch (attribute)
            {
                case GenerateIgnoreAttribute:
                    options.Ignore = true;
                    break;
                case GeneratePreferInterfacesAttribute:
                    options.PreferInterfaces = true;
                    break;
                case GenerateFormatNamesAttribute formatNamesAttribute:
                    options.FormatNames = formatNamesAttribute.FormatNames;
                    break;
                case GenerateNoHeaderAttribute:
                    options.AddHeader = false;
                    break;
                case GenerateNoHeaderVersionAttribute:
                    options.AddHeaderVersion = false;
                    break;
                case GenerateSuppressLintAttribute suppressLintAttribute:
                    options.AddToLintSuppression(suppressLintAttribute.Comment, suppressLintAttribute.Language);
                    break;
                case GenerateOnlySubTypesAttribute:
                    options.OnlySubTypes = true;
                    break;
                case GenerateNeverAttribute:
                    options.Never = true;
                    break;
                case GenerateClassAttribute classAttribute:
                    this.UpdateFromNaming(options, classAttribute);
                    break;
                case GenerateMemberAttribute memberAttribute:
                    this.UpdateFromNaming(options, memberAttribute);
                    if (memberAttribute.Type != null)
                    {
                        options.ReturnType = new TypeTransferObject
                        {
                            Name = memberAttribute.Type.Name,
                            Namespace = memberAttribute.Type.Namespace,
                            Type = memberAttribute.Type
                        };
                    }
                    else if (!string.IsNullOrEmpty(memberAttribute.TypeName))
                    {
                        options.ReturnType = new TypeTransferObject
                        {
                            Name = memberAttribute.TypeName
                        };
                    }
                    break;
                case GenerateImportAttribute importAttribute:
                    options.AddToImports(new Import(importAttribute.Type, importAttribute.FileName, importAttribute.TypeName));
                    break;
                case GenerateNoOptionalAttribute:
                    options.NoOptional = true;
                    break;
                case GenerateModelOutputAttribute modelOutputAttribute:
                    options.ModelOutput = modelOutputAttribute.RelativePath;
                    break;
            }
        }
        return options;
    }

    private void UpdateFromNaming(GeneratorOptions options, GenerateNamedAttribute attribute)
    {
        if (!string.IsNullOrEmpty(attribute.Name))
        {
            options.Rename = attribute.Name;
        }
        if (!string.IsNullOrEmpty(attribute.Replace))
        {
            options.AddToReplaceName(attribute.Replace!, attribute.With ?? string.Empty);
        }
    }

    private void UpdateFromDocumentation(GeneratorOptions options, string documentation)
    {
        if (documentation.Contains("GenerateIgnore") || documentation.Contains("Generator ignore"))
        {
            options.Ignore = true;
        }
    }
}
