// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 5.6.1.0
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// tslint:disable

export class CasingModel {
    public alllower: string;
    public ALLUPPER: string;
    public PascalCase: string;
    public camelCase: string;
    public snake_case: string;
    public UPPER_SNAKE_CASE: string;

    public constructor(init: Partial<CasingModel> = undefined) {
        Object.assign(this, init);
    }
}