using KY.Generator;

// The index.ts barrel file is generated by default. [GenerateForceIndex] requests it explicitly,
// so this example keeps working even if the surrounding configuration switches indexes off.
// Use [GenerateNoIndex] on the assembly or on a single type to opt out again.
[assembly: GenerateForceIndex]
