//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KY.Generator.AspDotNet.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KY.Generator.AspDotNet.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: 2,
        ///  &quot;generate&quot;: [
        ///    {
        ///      &quot;write&quot;: &quot;asp&quot;,
        ///      &quot;controller&quot;: {
        ///        &quot;namespace&quot;: &quot;KY.Generator.Test&quot;,
        ///        &quot;preloadModules&quot;: [
        ///          &quot;KY.Generator.Csharp.CsharpModule&quot;,
        ///          &quot;KY.Generator.TypeScript.TypeScriptModule&quot;,
        ///          &quot;KY.Generator.Reflection.ReflectionModule&quot;,
        ///          &quot;KY.Generator.AspDotNet.AspDotNetModule&quot;
        ///        ] 
        ///      }
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string generator_controller_core_generator {
            get {
                return ResourceManager.GetString("generator_controller_core_generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: 2,
        ///  &quot;generate&quot;: [
        ///    {
        ///      &quot;write&quot;: &quot;asp&quot;,
        ///      &quot;controller&quot;: {
        ///        &quot;namespace&quot;: &quot;KY.Generator.Test&quot;,
        ///        &quot;preloadModules&quot;: [
        ///          &quot;KY.Generator.Csharp.CsharpModule&quot;,
        ///          &quot;KY.Generator.TypeScript.TypeScriptModule&quot;,
        ///          &quot;KY.Generator.Reflection.ReflectionModule&quot;,
        ///          &quot;KY.Generator.AspDotNet.AspDotNetModule&quot;
        ///        ] 
        ///      }
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string generator_controller_generator {
            get {
                return ResourceManager.GetString("generator_controller_generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using KY.Generator;
        ///using KY.Generator.Output;
        ///using Microsoft.AspNetCore.Mvc;
        ///
        ///namespace KY.Generator.Test.Controllers
        ///{
        ///    [Route(&quot;[controller]&quot;)]
        ///    [Route(&quot;api/v1/[controller]&quot;)]
        ///    public partial class GeneratorController : Controller
        ///    {
        ///        private static readonly Dictionary&lt;string, MemoryOutput&gt; cache = new Dictionary&lt;string, MemoryOutput&gt;();
        ///
        ///        [HttpPost(&quot;[action]&quot;)]
        ///        public string Create(string [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GeneratorController_cs {
            get {
                return ResourceManager.GetString("GeneratorController_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using KY.Generator;
        ///using KY.Generator.Output;
        ///using Microsoft.AspNetCore.Mvc;
        ///
        ///namespace KY.Generator.Test.Controllers
        ///{
        ///    [Route(&quot;[controller]&quot;)]
        ///    [Route(&quot;api/v1/[controller]&quot;)]
        ///    public partial class GeneratorController : Controller
        ///    {
        ///        private static readonly Dictionary&lt;string, MemoryOutput&gt; cache = new Dictionary&lt;string, MemoryOutput&gt;();
        ///
        ///        [HttpPost(&quot;[action]&quot;)]
        ///        public string Create(string [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GeneratorCoreController_cs {
            get {
                return ResourceManager.GetString("GeneratorCoreController_cs", resourceCulture);
            }
        }
    }
}
