// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 5.5.2.0
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// tslint:disable

export class AnotherType {
    public stringField: string;
    public numberField: number;

    public constructor(init: Partial<AnotherType> = undefined) {
        Object.assign(this, init);
    }
}