// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 7.1.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

import { SecondType } from "./second-type";

export class TypeToRead {
    public stringProperty: string;
    public numberProperty: number;
    public secondTypeProperty: SecondType;
}

// outputid:8d8831d6-36e5-44aa-9876-6158694d0cc1
