using KY.Generator;

namespace JsonModelPathAndNamespace;

/// <summary>
/// Covers the three arguments of the JSON Model(...) syntax, none of which used to reach the output:
/// the relative path decides where the generated C# lands, the name replaces the one the reader derives
/// from the file (document.json would give Document), and the namespace is the one the C# declares.
/// The nested endpoint object becomes a model of its own - it keeps its property derived name, but has
/// to end up in the same folder and the same namespace as the root model.
/// </summary>
public class Generator : GeneratorFluentMain
{
    public override void Execute()
    {
        // The header stays on: it carries the <auto-generated> marker that keeps the compiler from
        // warning about the non nullable properties of the generated models, and the version it prints
        // is the assembly version, which does not move between previews.
        this.Read(read => read
                .Json(json => json.FromFile("Source/document.json")))
            .Write(write => write
                .Json(json => json.Model("Output", "Configuration", "KY.Generator.Tests.Json")
                                  .WithoutReader()));
    }
}
