using KY.Generator;

namespace AnnotationInBackground;

/// <summary>An Angular model generated by a command that runs in the background.</summary>
[GenerateAngularModel("Output")]
[GenerateInBackground]
public class AngularInBackground
{
    public string Property { get; set; } = "";
}
