<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net462</TargetFramework>
        <RootNamespace>KY.Generator</RootNamespace>
        <AssemblyName>KY.Generator</AssemblyName>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <OutputPath>bin\Debug\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <OutputPath>bin\Release\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="KY.Core.Common" Version="4.37.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Costura.Fody" Version="5.7.0" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Angular.Generator\KY.Generator.Angular.Generator.csproj" />
        <ProjectReference Include="..\Angular\KY.Generator.Angular.csproj" />
        <ProjectReference Include="..\AspDotNet.Generator\KY.Generator.AspDotNet.Generator.csproj" />
        <ProjectReference Include="..\AspDotNet\KY.Generator.AspDotNet.csproj" />
        <ProjectReference Include="..\Common.Generator\KY.Generator.Common.Generator.csproj" />
        <ProjectReference Include="..\Common\KY.Generator.Common.csproj" />
        <ProjectReference Include="..\Csharp.Generator\KY.Generator.CSharp.Generator.csproj" />
        <ProjectReference Include="..\CSharp\KY.Generator.Csharp.csproj" />
        <ProjectReference Include="..\Json.Generator\KY.Generator.Json.Generator.csproj" />
        <ProjectReference Include="..\Reflection.Generator\KY.Generator.Reflection.Generator.csproj" />
        <ProjectReference Include="..\Reflection\KY.Generator.Reflection.csproj" />
        <ProjectReference Include="..\Sqlite.Generator\KY.Generator.Sqlite.Generator.csproj" />
        <ProjectReference Include="..\Sqlite\KY.Generator.Sqlite.csproj" />
        <ProjectReference Include="..\Tsql.Generator\KY.Generator.Tsql.Generator.csproj" />
        <ProjectReference Include="..\Tsql\KY.Generator.Tsql.csproj" />
        <ProjectReference Include="..\TypeScript.Generator\KY.Generator.TypeScript.Generator.csproj" />
        <ProjectReference Include="..\TypeScript\KY.Generator.TypeScript.csproj" />
        <ProjectReference Include="..\Watchdog\KY.Generator.Watchdog.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="App.config" />
        <None Include="nuget.nuspec" />
    </ItemGroup>

</Project>
