// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 7.1.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class WeatherForecast {
    public date: Date = new Date(0);
    public temperatureC: number = 0;
    public temperatureF: number = 0;
    public summary: string | undefined;

    public constructor(init?: Partial<WeatherForecast>) {
        Object.assign(this, init);
    }
}

// outputid:fcbcab2d-b69d-4bef-a7d7-8760c70efc2b
