// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 10.1.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export interface TestModel {
    property?: string;
}

// outputid:068986b5-c7fe-4280-9442-8601b87f9114
