// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 10.0.1.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// ReSharper disable All

using System.CodeDom.Compiler;

namespace KY.Generator.Tests.Json
{
    [GeneratedCode("KY.Generator", "10.0.1.0")]
    public partial class Endpoint
    {
        public string Url { get; set; }
        public int Timeout { get; set; }
    }
}

// outputid:f6d9ac27-8b04-43dd-a165-a26cdf091e86
