// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 10.1.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class Address {
    public id: number = 0;
    public personId: number = 0;
    public street: string = "";
    public zipCode?: string;
    public city: string = "";

    public constructor(init?: Partial<Address>) {
        Object.assign(this, init);
    }
}

// outputid:a201bcc1-b978-4c70-9830-816caabacce7
