// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 10.0.1.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class Person {
    public id: number = 0;
    public firstName: string = "";
    public lastName: string = "";
    public birthday?: Date;
    public height?: number;
    public isActive: boolean = false;
    public publicId: string = "00000000-0000-0000-0000-000000000000";

    public constructor(init?: Partial<Person>) {
        Object.assign(this, init);
    }
}

// outputid:a201bcc1-b978-4c70-9830-816caabacce7
