// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 8.8.8.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class TypeToRead {
    public stringProperty: string;
    public numberProperty: number;

    public constructor(init?: Partial<TypeToRead>) {
        Object.assign(this, init);
    }
}

// outputid:fe448e28-7d8a-422b-9b2e-17ce462e3e81
