// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 10.0.1.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class WeatherForecast {
    public date: Date;
    public temperatureC: number;
    public summary?: string;

    public constructor(init?: Partial<WeatherForecast>) {
        Object.assign(this, init);
    }
}

// outputid:b3e17d45-6c28-4a0f-93d1-7e5a2b8c04f6
