// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 10.0.1.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// ReSharper disable All

#nullable enable
#pragma warning disable CS8618

using System.CodeDom.Compiler;

[GeneratedCode("KY.Generator", "10.0.1.0")]
public partial class Address
{
    public int Id { get; set; }
    public int PersonId { get; set; }
    public string Street { get; set; }
    public string? ZipCode { get; set; }
    public string City { get; set; }
}

// outputid:076fad40-9e04-4ecf-85e6-773413137608
