// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 10.0.1.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// ReSharper disable All

#nullable enable
#pragma warning disable CS8618

using System;
using System.CodeDom.Compiler;

[GeneratedCode("KY.Generator", "10.0.1.0")]
public partial class Person
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public DateTime? Birthday { get; set; }
    public decimal? Height { get; set; }
    public bool IsActive { get; set; }
    public Guid PublicId { get; set; }
}

// outputid:076fad40-9e04-4ecf-85e6-773413137608
