<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Company>KY-Programming</Company>
        <Version>10.0.1-preview.12</Version>
        <LangVersion>latest</LangVersion>
        <RootNamespace>KY.Generator</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>..\bin\Debug\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>..\bin\Release\</OutputPath>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common.Fluent\KY.Generator.Common.Fluent.csproj" />
    </ItemGroup>

</Project>
