// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 5.6.1.0
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// tslint:disable

export class AngularAsync {
    public property: string;

    public constructor(init: Partial<AngularAsync> = undefined) {
        Object.assign(this, init);
    }
}