// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 6.6.3.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class Class1 {
    public test: string;
}

// outputid:c38fa2cd-ab17-4d5e-954e-08358d615f1f
