// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 7.4.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class Class1 {
    public test: string;
}

// outputid:3d99e563-cf4b-42d2-aaca-9088f7a71b7e
