// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 5.4.0.0
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// tslint:disable

export class CasingModel {
    public alllower: string;
    public allupper: string;
    public pascalCase: string;
    public camelCase: string;
    public snakeCase: string;
    public upperSnakeCase: string;

    public constructor(init: Partial<CasingModel> = undefined) {
        Object.assign(this, init);
    }
}