// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 10.1.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class OtherSubType {
    public otherStringProperty: string = "";

    public constructor(init?: Partial<OtherSubType>) {
        Object.assign(this, init);
    }
}

// outputid:75e282f9-66b1-495f-be67-dcf13ec90073
