// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 8.8.7.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

import { OtherSubType } from "./other-sub-type";
import { SubType } from "./sub-type";

export class Types {
    public defaultSubTypeProperty: SubType;
    public changedSubTypeProperty: OtherSubType;
}

// outputid:75e282f9-66b1-495f-be67-dcf13ec90073
