// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 7.5.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class TypeToRead {
    public stringProperty: string;
    public numberProperty: number;
}

// outputid:3d295b41-82c1-4a99-b229-0e8b2cc2d0fd
