// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 5.4.0.0
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// tslint:disable

export enum ConnectionStatus {
    connecting = 0,
    connected = 1,
    disconnected = 2
}

export const ConnectionStatusValues = [0, 1, 2];
export const ConnectionStatusNames = ["connecting", "connected", "disconnected"];
export const ConnectionStatusValueMapping: { [key: number]: string } = { 0: "connecting", 1: "connected", 2: "disconnected" };
export const ConnectionStatusNameMapping: { [key: string]: number } = { "connecting": 0, "connected": 1, "disconnected": 2 };