// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 8.8.2.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class TypeToRead {
    public stringProperty: string;
    public numberProperty: number;
}

// outputid:7ea5334c-5e4f-406b-8224-3e8ee565e7f3
