// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 8.8.1.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class WeatherForecast {
    public date: Date = new Date(0);
    public temperatureC: number = 0;
    public temperatureF: number = 0;
    public summary: string | undefined;

    public constructor(init?: Partial<WeatherForecast>) {
        Object.assign(this, init);
    }
}

// outputid:fc26dcad-6b61-49d1-a5a1-1915cdb8dd48
