// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 0.8.0.0
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

import { SubType } from "./sub-type";

export class ExampleType {
    private stringPropertyField : string;
    public get stringProperty(): string {
        return this.stringPropertyField;
    }
    public set stringProperty(value: string ) {
        this.stringPropertyField = value;
    }
    private intPropertyField : number;
    public get intProperty(): number {
        return this.intPropertyField;
    }
    public set intProperty(value: number ) {
        this.intPropertyField = value;
    }
    private doublePropertyField : number;
    public get doubleProperty(): number {
        return this.doublePropertyField;
    }
    public set doubleProperty(value: number ) {
        this.doublePropertyField = value;
    }
    private boolPropertyField : boolean;
    public get boolProperty(): boolean {
        return this.boolPropertyField;
    }
    public set boolProperty(value: boolean ) {
        this.boolPropertyField = value;
    }
    private subTypePropertyField : SubType;
    public get subTypeProperty(): SubType {
        return this.subTypePropertyField;
    }
    public set subTypeProperty(value: SubType ) {
        this.subTypePropertyField = value;
    }
    private readonlyPropertyField : string;
    public get readonlyProperty(): string {
        return this.readonlyPropertyField;
    }
    private writeonlyPropertyField : string;
    public set writeonlyProperty(value: string ) {
        this.writeonlyPropertyField = value;
    }
}