// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 0.8.0.0
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

export class SubType {
    private propertyField : string;
    public get property(): string {
        return this.propertyField;
    }
    public set property(value: string ) {
        this.propertyField = value;
    }
}