// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 8.1.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class WeatherForecast {
    public date: Date;
    public temperatureC: number;
    public temperatureF: number;
    public summary: string;

    public constructor(init?: Partial<WeatherForecast>) {
        Object.assign(this, init);
    }
}

// outputid:fda66860-568e-45cd-bf6f-f019c18811be
