// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 8.4.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class SubType {
    public constructor(init?: Partial<SubType>) {
        Object.assign(this, init);
    }
}

// outputid:b69606d3-e998-4ef9-857c-ec0d10c33b3f
