// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 9.0.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

import { SubType } from "./sub-type";

export class WeatherForecast {
    public date?: Date = new Date(0);
    public temperatureC?: number = 0;
    public temperatureF?: number = 0;
    public summary?: string | undefined;
    public stringList?: string[] | undefined;
    public stringArray?: string[] | undefined;
    public stringDictionary?: { [key: string]: string; } | undefined;
    public object?: unknown | undefined;
    public subType?: SubType | undefined;
    public nullableDate?: Date | undefined;
    public requiredString: string | undefined;
    public requiredNotNullableString: string = "";
    public requiredInt: number = 0;
    public requiredNotNullableList: string[] = [];

    public constructor(init?: Partial<WeatherForecast>) {
        Object.assign(this, init);
    }
}

// outputid:b69606d3-e998-4ef9-857c-ec0d10c33b3f
