// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 6.7.4.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class TypeToRead {
    public stringProperty: string;
    public numberProperty: number;

    public constructor(init: Partial<TypeToRead> = undefined) {
        Object.assign(this, init);
    }
}

// outputid:224af25a-40c8-4e7e-bf28-0c28451d1171
