'use strict';

// Asserts what this example is about - the two options are only visible in the first lines of a
// generated file, which no type check would ever look at - and then type-checks the TypeScript and
// compiles the C# with the shared scripts.
//
// The last line of stdout is the machine readable result - the Builder reads that, not the exit code:
//
//     {"state":"passed","errors":0,"validated":3}

const fs = require('fs');
const path = require('path');

const OUTPUT = path.join(__dirname, 'Output', 'Models');

// file -> the comment that has to sit below the header. The TypeScript default, an overridden one, and
// the C# default. LegacyForecast.cs is written from the same model as legacy-forecast.ts and proves the
// override is limited to TypeScript.
const EXPECTED_LINT = {
    'weather-forecast.ts': '/* eslint-disable */',
    'legacy-forecast.ts': '// @ts-nocheck',
    'LegacyForecast.cs': '// ReSharper disable All',
    'Contact.cs': '// ReSharper disable All'
};

function fail(message) {
    console.log(`VALIDATION FAILED: ${message}`);
    console.log(JSON.stringify({ state: 'failed', errors: 1, validated: 0 }));
    process.exit(1);
}

function main() {
    if (!fs.existsSync(OUTPUT)) {
        fail('Output/Models does not exist - nothing was generated.');
    }

    for (const [name, comment] of Object.entries(EXPECTED_LINT)) {
        const file = path.join(OUTPUT, name);
        if (!fs.existsSync(file)) {
            fail(`Output/Models/${name} was not generated.`);
        }
        const content = fs.readFileSync(file, 'utf8');

        // GenerateHeaderWithoutVersion: the header names the generator, never a version behind it.
        const generatedWith = /This code was generated with (.+)/.exec(content);
        if (!generatedWith) {
            fail(`${name} has no <auto-generated> header.`);
        }
        if (/\d+\.\d+/.test(generatedWith[1])) {
            fail(`${name} still carries a version in its header: "${generatedWith[1].trim()}".`);
        }

        if (!content.includes(comment)) {
            fail(`${name} does not contain ${comment}.`);
        }

        // Exactly one comment, so an override meant for one language can not leak into another.
        for (const other of new Set(Object.values(EXPECTED_LINT))) {
            if (other !== comment && content.includes(other)) {
                fail(`${name} contains ${other}, which belongs to another language.`);
            }
        }

        // The linter comment is one line, not one per linter that ever existed.
        if (content.includes('tslint:disable')) {
            fail(`${name} still contains the dead // tslint:disable.`);
        }
    }

    console.log(`${Object.keys(EXPECTED_LINT).length} generated file(s) checked for header and linter comment.`);

    const typeScript = require('../../../../Tests/Shared/Scripts/validate-files').check(OUTPUT);
    const csharp = require('../../../../Tests/Shared/Scripts/validate-csharp').check(OUTPUT);
    const errors = typeScript.errors + csharp.errors;
    const validated = typeScript.validated + csharp.validated;
    console.log(JSON.stringify({ state: errors > 0 ? 'failed' : 'passed', errors, validated }));
    process.exit(errors > 0 ? 1 : 0);
}

main();
