// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 3.3.0.0
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// tslint:disable

export class Value {
    public id: number;
    public text: string;

    public constructor(init: Partial<Value> = undefined) {
        Object.assign(this, init);
    }
}