// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 8.2.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class GenericSubType<TOne, TTwo> {
    public single: TOne;
    public single2: string;
    public enumerable: TOne[];
    public list: TTwo[];
    public stringList: string[];
}

// outputid:bad14fb5-07e1-427f-a980-39a198977f92
