<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Company>KY-Programming</Company>
        <Version>10.2.0</Version>
        <LangVersion>latest</LangVersion>
        <RootNamespace>KY.Generator</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <OutputPath>..\bin\Debug</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <OutputPath>..\bin\Release</OutputPath>
        <NoWarn>1701;1702;1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="KY.Core.Common" Version="10.1.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common.Fluent\KY.Generator.Common.Fluent.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="KY.Generator.AspDotNet.Fluent.csproj.DotSettings" />
    </ItemGroup>

</Project>
