using System;
using System.Text;
using KY.Core;
using KY.Core.DataAccess;

namespace KY.Generator.Output
{
    public class OutputWriteAction : IOutputAction
    {
        private bool executed;
        public string FilePath { get; }
        public string Content { get; }
        public Guid? OutputId { get; }

        public OutputWriteAction(string filePath, string content, Guid? outputId)
        {
            this.FilePath = filePath;
            this.Content = content;
            this.OutputId = outputId;
        }

        public void Execute()
        {
            if (this.executed)
            {
                return;
            }
            this.executed = true;
            FileSystem.CreateDirectory(FileSystem.Parent(this.FilePath));
            if (!FileSystem.FileExists(this.FilePath))
            {
                Logger.Trace($"Write file {this.FilePath}");
                this.WriteFile();
                return;
            }
            string content = FileSystem.ReadAllText(this.FilePath);
            if (this.Content == content)
            {
                Logger.Trace($"File has no changes {this.FilePath}");
            }
            else if (content.Length == 0 || this.OutputId == null && this.IsGeneratedFile(content) || this.IsSameOutputId(content))
            {
                Logger.Trace($"Overwrite file {this.FilePath}");
                this.WriteFile();
            }
            else
            {
                Logger.Error($"Can not overwrite file {this.FilePath}. File to overwrite is not a generated file or generated by a different project. Please delete file manually!");
            }
        }

        private void WriteFile()
        {
            FileSystem.WriteAllText(this.FilePath, this.Content, Encoding.UTF8);
        }

        private bool IsGeneratedFile(string content)
        {
            return content.Contains("<auto-generated>");
        }

        private bool IsSameOutputId(string content)
        {
            return content.Contains($"outputid:{this.OutputId}");
        }
    }
}