//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KY.Generator.Tsql.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KY.Generator.Tsql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected TRepository Repository { get; }
        ///
        ///        protected ODataController(TRepository repository = default(TRepository))
        ///        {
        ///            this.Repository = repository;
        ///        }
        ///
        ///        protected IQueryable&lt;TItem&gt; GetInternal()
        ///        {
        ///            try
        ///            {
        ///                this.OnGetting();
        ///                IQueryable&lt;TItem&gt; result = this.Repository.Read();
        ///                return this.OnGetted(result);
        ///            }
        ///            catch (Exception exception)
        ///            {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ODataController {
            get {
                return ResourceManager.GetString("ODataController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected TContext DataContext { get; }
        ///
        ///        protected ODataRepository(TContext dataContext = null)
        ///        {
        ///            this.DataContext = dataContext ?? Activator.CreateInstance&lt;TContext&gt;();
        ///        }
        ///
        ///        protected ODataRepository(ODataRepository&lt;TContext&gt; repository)
        ///        {
        ///            this.DataContext = repository.DataContext;
        ///        }
        ///
        ///        public void Dispose()
        ///        {
        ///            this.DataContext?.Dispose();
        ///        }.
        /// </summary>
        internal static string ODataRepository1 {
            get {
                return ResourceManager.GetString("ODataRepository1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected DbSet&lt;TItem&gt; DataSet { get; }
        ///
        ///        protected ODataRepository(TContext dataContext = null)
        ///            : base(dataContext)
        ///        {
        ///            this.DataSet = this.DataContext.Set&lt;TItem&gt;();
        ///        }
        ///
        ///        protected ODataRepository(ODataRepository&lt;TContext&gt; repository)
        ///            : base(repository)
        ///        {
        ///            this.DataSet = this.DataContext.Set&lt;TItem&gt;();
        ///        }
        ///
        ///        public virtual TItem Create(TItem item)
        ///        {
        ///            TItem result = this.DataSet.A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ODataRepository2 {
            get {
                return ResourceManager.GetString("ODataRepository2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    c.COLUMN_NAME,
        ///    c.DATA_TYPE,
        ///    c.IS_NULLABLE,
        ///    c.ORDINAL_POSITION,
        ///    c.CHARACTER_MAXIMUM_LENGTH,
        ///    CASE WHEN p.ORDINAL_POSITION &gt; 0 THEN 1 ELSE 0 END AS IS_PRIMARY,
        ///    f.CONSTRAINT_NAME as FOREIGN_NAME,
        ///    f.FOREIGN_TABLE_NAME,
        ///    COLUMNPROPERTY(OBJECT_ID(c.TABLE_SCHEMA + &apos;.&apos; + c.TABLE_NAME), c.COLUMN_NAME, &apos;IsIdentity&apos;) AS IS_IDENTITY,
        ///    (CASE WHEN c.CHARACTER_SET_NAME = &apos;UNICODE&apos; THEN 1 ELSE 0 END) AS IS_UNICODE,
        ///    c.NUMERIC_PRECISION,
        ///    c.NUMERIC_SCALE,
        ///    c. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadColumnsCommand {
            get {
                return ResourceManager.GetString("ReadColumnsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	PARAMETER_NAME,
        ///	DATA_TYPE,
        ///	ORDINAL_POSITION
        ///FROM INFORMATION_SCHEMA.PARAMETERS
        ///WHERE SPECIFIC_SCHEMA = @schema
        ///	AND SPECIFIC_NAME = @name;.
        /// </summary>
        internal static string ReadParametersCommand {
            get {
                return ResourceManager.GetString("ReadParametersCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///	s.[name] AS COLUMN_NAME,
        ///	t.[name] AS DATA_TYPE,
        ///	case when s.is_nullable = 1 then &apos;YES&apos; else &apos;NO&apos; end AS IS_NULLABLE,
        ///	s.column_ordinal AS ORDINAL_POSITION,
        ///	null AS CHARACTER_MAXIMUM_LENGTH,
        ///	0 AS IS_PRIMARY,
        ///	null as FOREIGN_NAME,
        ///	null as FOREIGN_TABLE_NAME,
        ///	0 as IS_IDENTITY,
        ///	0 as IS_UNICODE,
        ///	s.[precision] as NUMERIC_PRECISION,
        ///	cast(s.scale as int) as NUMERIC_SCALE,
        ///	null as COLUMN_DEFAULT
        ///from sys.dm_exec_describe_first_result_set(&apos;exec {0}&apos;,NULL,1) as s
        ///	left join sys.types [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadResultCommand {
            get {
                return ResourceManager.GetString("ReadResultCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT {0}
        ///FROM {1}.{2}.
        /// </summary>
        internal static string ReadValuesCommand {
            get {
                return ResourceManager.GetString("ReadValuesCommand", resourceCulture);
            }
        }
    }
}
