// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 6.0.0.0
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// tslint:disable

export class TypeToRead {
    public stringProperty: string;
    public numberProperty: number;

    public constructor(init: Partial<TypeToRead> = undefined) {
        Object.assign(this, init);
    }
}

// outputid:4a02ee87-ce35-4761-a2fe-498c859c7974