// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 10.0.1.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export interface TestModel {
    property?: string;
}

// outputid:9f467c28-0164-494c-976c-6c7d360a372d
