// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated with KY.Generator 10.1.0.0
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
/* eslint-disable */
// tslint:disable

export class WeatherForecast {
    public date: Date = new Date(0);
    public temperatureC: number = 0;
    public temperatureF: number = 0;
    public summary?: string;

    public constructor(init?: Partial<WeatherForecast>) {
        Object.assign(this, init);
    }
}

// outputid:c641eaed-e8b2-49b6-b0d9-8ba916d91825
